In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\SARANYA GANESH\AppData\Local\Programs\Python\Python312\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\SARANYA GANESH\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\SARANYA GANESH\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\SARANYA GANESH\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\SARANYA GANESH\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [9]:
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])
print(df)
print(df.head())
print(df.tail())	
print(df.info())	
print(df.describe())

    Name  Age
0  Alice   25
1    Bob   30
    Name  Age
0  Alice   25
1    Bob   30
    Name  Age
0  Alice   25
1    Bob   30
<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes
None
             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [11]:
print(df['Name'])
df[['Name', 'Age']]

0    Alice
1      Bob
Name: Name, dtype: str

    Name  Age
0  Alice   25
1    Bob   30

In [14]:
print(df.loc[0])
print(df.iloc[1])

Name    Alice
Age        25
Name: 0, dtype: object
Name    Bob
Age      30
Name: 1, dtype: object

In [16]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [20]:


df.drop('Age', axis=1, inplace=True)

KeyError: "['Age'] not found in axis"

In [24]:
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])
df.drop('Age', axis=1, inplace=True) 
print(df)

    Name
0  Alice
1    Bob